name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: idsarra
        password: sarra1MAMA2rim3.
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag idsarra/image:imagedocker
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push Docker Image to Docker Hub
        run: docker push idsarra/image:imagedocker