name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag idsarra/sarra:${GITHUB_SHA::8}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push Docker Image to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/sarra:${GITHUB_SHA::8}